# ── Font ─────────────────────────────────────────────────
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        11.0

# ── Cursor ───────────────────────────────────────────────
cursor                     #ff4444
cursor_text_color          #111111
cursor_shape               block
cursor_blink_interval      0.4

# ── Window ───────────────────────────────────────────────
window_padding_width       14
window_border_width        1px
active_border_color        #ff4444
inactive_border_color      #1a1a1a
background_opacity         0.92
background                 #0a0a0a
foreground                 #e0e0e0

# ── Cores Principais (Noir / Caveirão) ───────────────────
selection_background    #2a2a2a
selection_foreground    #ffffff

url_color               #ff4444
url_style               curly

# Black
color0 #1a1a1a
color8 #333333

# Red (Accent)
color1 #771111
color9 #ff4444

# Green (Bone White/Grey)
color2 #444444
color10 #555555

# Yellow (Bege suave do wallpaper)
color3 #dcdccc
color11 #ffffff

# Blue (Deep Grey)
color4 #222222
color12 #444444

# Magenta
color5 #555555
color13 #777777

# Cyan
color6 #888888
color14 #aaaaaa

# White
color7 #b0b0b0
color15 #ffffff

# Tab bar
active_tab_background   #111111
active_tab_foreground   #ff4444
inactive_tab_background #0a0a0a
inactive_tab_foreground #444444
tab_bar_background      #050505
